/// Flutter icons Note
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Note
///      fonts:
///       - asset: fonts/Note.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Note {
  Note._();

  static const _kFontFam = 'Note';
  static const _kFontPkg = null;

  static const IconData sticky_note_2_24px = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
